apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-music-deployment
  labels:
    app: server-music
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server-music

  template:
    metadata:
      name: server-music
      labels:
        app: server-music
    spec:
      containers:
        - image: server-stream-music
          name: server-music-pod
          imagePullPolicy: Never
          resources: {}
          ports:
            - containerPort: 5000
