apiVersion: v1
kind: Pod
metadata:
  name: server-music-pod
spec:
  containers:
    - image: server-stream-music
      name: server-music-pod
      imagePullPolicy: Never
      resources: {}
      ports:
        - containerPort: 5000
