apiVersion: v1
kind: Service
metadata:
  name: server-music-service
  labels:
    run: server-music
spec:
  ports:
    - port: 5000
      protocol: TCP
  selector:
    app: server-music
  type: NodePort
