apiVersion: v1
kind: Service
metadata:
  name: server-music-service
  labels:
    run: server-music
spec:
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  selector:
    app: server-music
  type: NodePort
